name=7Semi BMM150
version=1.0.0
author=7Semi
maintainer=7Semi <info@7semi.com>
sentence=Lightweight and efficient BMI150 pressure and temperature sensor library.
paragraph=Provides a clean, high-performance interface for Bosch BMI150 sensors over I2C and SPI. Includes support for FIFO, interrupts, filtering, oversampling, and altitude calculation. Designed for embedded efficiency and ease of use.
category=Sensors
url=https://github.com/7semi-solutions/7Semi-BMM150
architectures=*
Includes=7Semi_BMM150
depends=
